// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailGallery.Data;

namespace RailGallery.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210924172553_New seed data")]
    partial class Newseeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlbumImage", b =>
                {
                    b.Property<int>("AlbumsAlbumID")
                        .HasColumnType("int");

                    b.Property<int>("ImagesImageID")
                        .HasColumnType("int");

                    b.HasKey("AlbumsAlbumID", "ImagesImageID");

                    b.HasIndex("ImagesImageID");

                    b.ToTable("AlbumImage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("RailGallery.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumPrivacy")
                        .HasColumnType("int");

                    b.Property<string>("AlbumTitle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AlbumID");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("RailGallery.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RailGallery.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryTitle = "Night Shots"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryTitle = "Golden Hour"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryTitle = "Accidents"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryTitle = "In-Cab Photos"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryTitle = "Passenger Trains"
                        },
                        new
                        {
                            CategoryID = 6,
                            CategoryTitle = "Freight Trains"
                        },
                        new
                        {
                            CategoryID = 7,
                            CategoryTitle = "Steam Locomotives"
                        },
                        new
                        {
                            CategoryID = 8,
                            CategoryTitle = "Bridges"
                        });
                });

            modelBuilder.Entity("RailGallery.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ImageID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("RailGallery.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.HasKey("FavoriteID");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ImageID");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RailGallery.Models.Image", b =>
                {
                    b.Property<int>("ImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ImageDescription")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImagePrivacy")
                        .HasColumnType("int");

                    b.Property<int>("ImageStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImageTakenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("ImageUploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int?>("LocomotiveID")
                        .HasColumnType("int");

                    b.HasKey("ImageID");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryID");

                    b.HasIndex("LocationID");

                    b.HasIndex("LocomotiveID");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("RailGallery.Models.Like", b =>
                {
                    b.Property<int>("LikeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ImageID")
                        .HasColumnType("int");

                    b.HasKey("LikeID");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ImageID");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("RailGallery.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            LocationName = "Ontario, Canada"
                        },
                        new
                        {
                            LocationID = 2,
                            LocationName = "New York, USA"
                        },
                        new
                        {
                            LocationID = 3,
                            LocationName = "New Jersey, USA"
                        },
                        new
                        {
                            LocationID = 4,
                            LocationName = "British Columbia, Canada"
                        },
                        new
                        {
                            LocationID = 5,
                            LocationName = "Nova Scotia, Canada"
                        },
                        new
                        {
                            LocationID = 6,
                            LocationName = "Virginia, USA"
                        },
                        new
                        {
                            LocationID = 7,
                            LocationName = "Manitoba, Canada"
                        },
                        new
                        {
                            LocationID = 8,
                            LocationName = "Alberta, Canada"
                        });
                });

            modelBuilder.Entity("RailGallery.Models.Locomotive", b =>
                {
                    b.Property<int>("LocomotiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("LocomotiveBuilt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocomotiveModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocomotiveID");

                    b.ToTable("Locomotives");

                    b.HasData(
                        new
                        {
                            LocomotiveID = 1,
                            LocomotiveBuilt = new DateTime(1964, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "Steam 4-6-0"
                        },
                        new
                        {
                            LocomotiveID = 2,
                            LocomotiveBuilt = new DateTime(1997, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "GE ES44AC"
                        },
                        new
                        {
                            LocomotiveID = 3,
                            LocomotiveBuilt = new DateTime(2000, 2, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "GE AC4400CWM"
                        },
                        new
                        {
                            LocomotiveID = 4,
                            LocomotiveBuilt = new DateTime(1956, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "R160"
                        },
                        new
                        {
                            LocomotiveID = 5,
                            LocomotiveBuilt = new DateTime(1994, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "GE P42DC"
                        },
                        new
                        {
                            LocomotiveID = 6,
                            LocomotiveBuilt = new DateTime(2007, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "GC 546"
                        },
                        new
                        {
                            LocomotiveID = 7,
                            LocomotiveBuilt = new DateTime(1956, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "Steam 2-8-4"
                        },
                        new
                        {
                            LocomotiveID = 8,
                            LocomotiveBuilt = new DateTime(2009, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LocomotiveModel = "AMT 1325"
                        });
                });

            modelBuilder.Entity("AlbumImage", b =>
                {
                    b.HasOne("RailGallery.Models.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsAlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailGallery.Models.Image", null)
                        .WithMany()
                        .HasForeignKey("ImagesImageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailGallery.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RailGallery.Models.Album", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Albums")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("RailGallery.Models.Comment", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Comments")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RailGallery.Models.Image", "Image")
                        .WithMany("Comments")
                        .HasForeignKey("ImageID");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RailGallery.Models.Favorite", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Favorites")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RailGallery.Models.Image", "Image")
                        .WithMany("Favorites")
                        .HasForeignKey("ImageID");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RailGallery.Models.Image", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Images")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RailGallery.Models.Category", "Category")
                        .WithMany("Images")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailGallery.Models.Location", "Location")
                        .WithMany("Images")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailGallery.Models.Locomotive", "Locomotive")
                        .WithMany("Images")
                        .HasForeignKey("LocomotiveID");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Locomotive");
                });

            modelBuilder.Entity("RailGallery.Models.Like", b =>
                {
                    b.HasOne("RailGallery.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Likes")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("RailGallery.Models.Image", "Image")
                        .WithMany("Likes")
                        .HasForeignKey("ImageID");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("RailGallery.Models.ApplicationUser", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Images");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("RailGallery.Models.Category", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("RailGallery.Models.Image", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("RailGallery.Models.Location", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("RailGallery.Models.Locomotive", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
